// Generated by scripts/generate-airports.mjs — do not edit by hand.
// Source: data/airports.csv + data/runways.csv (OurAirports).

export interface Runway {
  leIdent: string;
  heIdent: string;
  le: [number, number];
  he: [number, number];
  widthFt: number;
}

export interface AirportCatalogEntry {
  icao: string;
  iata: string;
  name: string;
  /** Short label for the control panel. */
  label: string;
  centerLat: number;
  centerLon: number;
  runways: Runway[];
}

export interface AirportGroup {
  label: string;
  icaos: string[];
}

export const DEFAULT_AIRPORT_ICAO = "OMDB";

export const AIRPORT_GROUPS: AirportGroup[] = [
  {
    "label": "New York area",
    "icaos": [
      "KJFK",
      "KEWR",
      "KLGA"
    ]
  },
  {
    "label": "Busiest in the world",
    "icaos": [
      "KATL",
      "OMDB",
      "KDFW",
      "EGLL",
      "LTFM",
      "KDEN",
      "WSSS",
      "KLAX",
      "KORD",
      "VIDP"
    ]
  }
];

export const AIRPORT_CATALOG: Record<string, AirportCatalogEntry> = {
  "KJFK": {
    "icao": "KJFK",
    "iata": "JFK",
    "name": "John F. Kennedy International Airport",
    "centerLat": 40.639447,
    "centerLon": -73.779317,
    "label": "JFK — John F. Kennedy International Airport",
    "runways": [
      {
        "leIdent": "04L",
        "heIdent": "22R",
        "le": [
          40.622002,
          -73.785599
        ],
        "he": [
          40.6488,
          -73.764702
        ],
        "widthFt": 200
      },
      {
        "leIdent": "04R",
        "heIdent": "22L",
        "le": [
          40.625401,
          -73.770302
        ],
        "he": [
          40.645199,
          -73.754898
        ],
        "widthFt": 200
      },
      {
        "leIdent": "13L",
        "heIdent": "31R",
        "le": [
          40.657799,
          -73.790199
        ],
        "he": [
          40.6437,
          -73.7593
        ],
        "widthFt": 200
      },
      {
        "leIdent": "13R",
        "heIdent": "31L",
        "le": [
          40.648399,
          -73.816704
        ],
        "he": [
          40.627899,
          -73.771599
        ],
        "widthFt": 200
      }
    ]
  },
  "KEWR": {
    "icao": "KEWR",
    "iata": "EWR",
    "name": "Newark Liberty International Airport",
    "centerLat": 40.6894,
    "centerLon": -74.170545,
    "label": "EWR — Newark Liberty International Airport",
    "runways": [
      {
        "leIdent": "11",
        "heIdent": "29",
        "le": [
          40.702815,
          -74.180748
        ],
        "he": [
          40.701203,
          -74.156502
        ],
        "widthFt": 150
      },
      {
        "leIdent": "4L",
        "heIdent": "22R",
        "le": [
          40.675392,
          -74.179456
        ],
        "he": [
          40.70257,
          -74.16217
        ],
        "widthFt": 150
      },
      {
        "leIdent": "4R",
        "heIdent": "22L",
        "le": [
          40.677588,
          -74.174253
        ],
        "he": [
          40.702299,
          -74.158539
        ],
        "widthFt": 150
      }
    ]
  },
  "KLGA": {
    "icao": "KLGA",
    "iata": "LGA",
    "name": "LaGuardia Airport",
    "centerLat": 40.777199,
    "centerLon": -73.872597,
    "label": "LGA — LaGuardia Airport",
    "runways": [
      {
        "leIdent": "04",
        "heIdent": "22",
        "le": [
          40.769199,
          -73.884102
        ],
        "he": [
          40.7854,
          -73.870697
        ],
        "widthFt": 150
      },
      {
        "leIdent": "13",
        "heIdent": "31",
        "le": [
          40.782299,
          -73.878502
        ],
        "he": [
          40.772099,
          -73.857101
        ],
        "widthFt": 150
      }
    ]
  },
  "KATL": {
    "icao": "KATL",
    "iata": "ATL",
    "name": "Hartsfield Jackson Atlanta International Airport",
    "centerLat": 33.6367,
    "centerLon": -84.428101,
    "label": "ATL — Hartsfield Jackson Atlanta International Airport",
    "runways": [
      {
        "leIdent": "08L",
        "heIdent": "26R",
        "le": [
          33.649502,
          -84.439003
        ],
        "he": [
          33.649502,
          -84.4095
        ],
        "widthFt": 150
      },
      {
        "leIdent": "08R",
        "heIdent": "26L",
        "le": [
          33.646801,
          -84.4384
        ],
        "he": [
          33.646801,
          -84.405502
        ],
        "widthFt": 150
      },
      {
        "leIdent": "09L",
        "heIdent": "27R",
        "le": [
          33.634701,
          -84.447998
        ],
        "he": [
          33.634701,
          -84.408897
        ],
        "widthFt": 150
      },
      {
        "leIdent": "09R",
        "heIdent": "27L",
        "le": [
          33.631802,
          -84.447998
        ],
        "he": [
          33.631802,
          -84.418404
        ],
        "widthFt": 150
      },
      {
        "leIdent": "10",
        "heIdent": "28",
        "le": [
          33.6203,
          -84.447899
        ],
        "he": [
          33.6203,
          -84.418297
        ],
        "widthFt": 150
      }
    ]
  },
  "OMDB": {
    "icao": "OMDB",
    "iata": "DXB",
    "name": "Dubai International Airport",
    "centerLat": 25.24979,
    "centerLon": 55.370992,
    "label": "DXB — Dubai International Airport",
    "runways": [
      {
        "leIdent": "12L",
        "heIdent": "30R",
        "le": [
          25.264627,
          55.350422
        ],
        "he": [
          25.247709,
          55.380932
        ],
        "widthFt": 197
      },
      {
        "leIdent": "12R",
        "heIdent": "30L",
        "le": [
          25.252836,
          55.364376
        ],
        "he": [
          25.23592,
          55.394882
        ],
        "widthFt": 197
      }
    ]
  },
  "KDFW": {
    "icao": "KDFW",
    "iata": "DFW",
    "name": "Dallas Fort Worth International Airport",
    "centerLat": 32.896801,
    "centerLon": -97.038002,
    "label": "DFW — Dallas Fort Worth International Airport",
    "runways": [
      {
        "leIdent": "13L",
        "heIdent": "31R",
        "le": [
          32.912601,
          -97.0215
        ],
        "he": [
          32.895,
          -97.000801
        ],
        "widthFt": 200
      },
      {
        "leIdent": "13R",
        "heIdent": "31L",
        "le": [
          32.909599,
          -97.083099
        ],
        "he": [
          32.890301,
          -97.063301
        ],
        "widthFt": 150
      },
      {
        "leIdent": "17C",
        "heIdent": "35C",
        "le": [
          32.915699,
          -97.026001
        ],
        "he": [
          32.878899,
          -97.026199
        ],
        "widthFt": 150
      },
      {
        "leIdent": "17L",
        "heIdent": "35R",
        "le": [
          32.8983,
          -97.009804
        ],
        "he": [
          32.875,
          -97.009903
        ],
        "widthFt": 150
      },
      {
        "leIdent": "17R",
        "heIdent": "35L",
        "le": [
          32.915699,
          -97.0299
        ],
        "he": [
          32.878899,
          -97.030098
        ],
        "widthFt": 200
      },
      {
        "leIdent": "18L",
        "heIdent": "36R",
        "le": [
          32.915798,
          -97.050697
        ],
        "he": [
          32.879002,
          -97.050903
        ],
        "widthFt": 200
      },
      {
        "leIdent": "18R",
        "heIdent": "36L",
        "le": [
          32.915798,
          -97.054604
        ],
        "he": [
          32.879002,
          -97.054802
        ],
        "widthFt": 150
      }
    ]
  },
  "EGLL": {
    "icao": "EGLL",
    "iata": "LHR",
    "name": "London Heathrow Airport",
    "centerLat": 51.470748,
    "centerLon": -0.459909,
    "label": "LHR — London Heathrow Airport",
    "runways": [
      {
        "leIdent": "09L",
        "heIdent": "27R",
        "le": [
          51.47749,
          -0.489439
        ],
        "he": [
          51.477681,
          -0.433227
        ],
        "widthFt": 164
      },
      {
        "leIdent": "09R",
        "heIdent": "27L",
        "le": [
          51.46478,
          -0.486808
        ],
        "he": [
          51.464957,
          -0.434048
        ],
        "widthFt": 164
      }
    ]
  },
  "LTFM": {
    "icao": "LTFM",
    "iata": "IST",
    "name": "İstanbul Airport",
    "centerLat": 41.274874,
    "centerLon": 28.732136,
    "label": "IST — İstanbul Airport",
    "runways": [
      {
        "leIdent": "16L",
        "heIdent": "34R",
        "le": [
          41.298599,
          28.7092
        ],
        "he": [
          41.2649,
          28.7099
        ],
        "widthFt": 147
      },
      {
        "leIdent": "16R",
        "heIdent": "34L",
        "le": [
          41.298599,
          28.706751
        ],
        "he": [
          41.264839,
          28.707411
        ],
        "widthFt": 196
      },
      {
        "leIdent": "17L",
        "heIdent": "35R",
        "le": [
          41.298828,
          28.727039
        ],
        "he": [
          41.261921,
          28.72776
        ],
        "widthFt": 196
      },
      {
        "leIdent": "17R",
        "heIdent": "35L",
        "le": [
          41.298801,
          28.724501
        ],
        "he": [
          41.261902,
          28.7253
        ],
        "widthFt": 147
      },
      {
        "leIdent": "18",
        "heIdent": "36",
        "le": [
          41.289799,
          28.756201
        ],
        "he": [
          41.262199,
          28.756701
        ],
        "widthFt": 148
      }
    ]
  },
  "KDEN": {
    "icao": "KDEN",
    "iata": "DEN",
    "name": "Denver International Airport",
    "centerLat": 39.860027,
    "centerLon": -104.673792,
    "label": "DEN — Denver International Airport",
    "runways": [
      {
        "leIdent": "07",
        "heIdent": "25",
        "le": [
          39.8409,
          -104.726997
        ],
        "he": [
          39.840698,
          -104.683998
        ],
        "widthFt": 150
      },
      {
        "leIdent": "08",
        "heIdent": "26",
        "le": [
          39.877602,
          -104.662003
        ],
        "he": [
          39.877201,
          -104.619003
        ],
        "widthFt": 150
      },
      {
        "leIdent": "16L",
        "heIdent": "34R",
        "le": [
          39.896999,
          -104.686996
        ],
        "he": [
          39.864101,
          -104.686996
        ],
        "widthFt": 150
      },
      {
        "leIdent": "16R",
        "heIdent": "34L",
        "le": [
          39.895802,
          -104.695999
        ],
        "he": [
          39.851898,
          -104.696999
        ],
        "widthFt": 200
      },
      {
        "leIdent": "17L",
        "heIdent": "35R",
        "le": [
          39.865002,
          -104.640999
        ],
        "he": [
          39.832001,
          -104.641998
        ],
        "widthFt": 150
      },
      {
        "leIdent": "17R",
        "heIdent": "35L",
        "le": [
          39.861198,
          -104.660004
        ],
        "he": [
          39.8283,
          -104.661003
        ],
        "widthFt": 150
      }
    ]
  },
  "WSSS": {
    "icao": "WSSS",
    "iata": "SIN",
    "name": "Singapore Changi Airport",
    "centerLat": 1.35019,
    "centerLon": 103.994003,
    "label": "SIN — Singapore Changi Airport",
    "runways": [
      {
        "leIdent": "02C",
        "heIdent": "20C",
        "le": [
          1.3288,
          103.985001
        ],
        "he": [
          1.36213,
          103.999001
        ],
        "widthFt": 197
      },
      {
        "leIdent": "02L",
        "heIdent": "20R",
        "le": [
          1.34897,
          103.977997
        ],
        "he": [
          1.38241,
          103.991997
        ],
        "widthFt": 197
      }
    ]
  },
  "KLAX": {
    "icao": "KLAX",
    "iata": "LAX",
    "name": "Los Angeles International Airport",
    "centerLat": 33.942501,
    "centerLon": -118.407997,
    "label": "LAX — Los Angeles International Airport",
    "runways": [
      {
        "leIdent": "6L",
        "heIdent": "24R",
        "le": [
          33.949119,
          -118.431187
        ],
        "he": [
          33.952112,
          -118.401954
        ],
        "widthFt": 150
      },
      {
        "leIdent": "6R",
        "heIdent": "24L",
        "le": [
          33.94682,
          -118.434693
        ],
        "he": [
          33.95047,
          -118.399063
        ],
        "widthFt": 150
      },
      {
        "leIdent": "7L",
        "heIdent": "25R",
        "le": [
          33.935556,
          -118.422089
        ],
        "he": [
          33.939881,
          -118.379794
        ],
        "widthFt": 150
      },
      {
        "leIdent": "7R",
        "heIdent": "25L",
        "le": [
          33.933659,
          -118.419074
        ],
        "he": [
          33.937371,
          -118.3827
        ],
        "widthFt": 200
      }
    ]
  },
  "KORD": {
    "icao": "KORD",
    "iata": "ORD",
    "name": "Chicago O'Hare International Airport",
    "centerLat": 41.9786,
    "centerLon": -87.9048,
    "label": "ORD — Chicago O'Hare International Airport",
    "runways": [
      {
        "leIdent": "04L",
        "heIdent": "22R",
        "le": [
          41.981701,
          -87.913902
        ],
        "he": [
          41.997501,
          -87.8964
        ],
        "widthFt": 150
      },
      {
        "leIdent": "04R",
        "heIdent": "22L",
        "le": [
          41.9533,
          -87.899399
        ],
        "he": [
          41.969898,
          -87.879799
        ],
        "widthFt": 150
      },
      {
        "leIdent": "09C",
        "heIdent": "27C",
        "le": [
          41.98831,
          -87.931584
        ],
        "he": [
          41.988326,
          -87.890211
        ],
        "widthFt": 200
      },
      {
        "leIdent": "09L",
        "heIdent": "27R",
        "le": [
          42.002831,
          -87.926674
        ],
        "he": [
          42.002831,
          -87.899086
        ],
        "widthFt": 150
      },
      {
        "leIdent": "09R",
        "heIdent": "27L",
        "le": [
          41.983898,
          -87.91835
        ],
        "he": [
          41.983898,
          -87.889053
        ],
        "widthFt": 150
      },
      {
        "leIdent": "10C",
        "heIdent": "28C",
        "le": [
          41.965698,
          -87.931503
        ],
        "he": [
          41.965698,
          -87.8918
        ],
        "widthFt": 200
      },
      {
        "leIdent": "10L",
        "heIdent": "28R",
        "le": [
          41.969002,
          -87.931503
        ],
        "he": [
          41.969101,
          -87.883698
        ],
        "widthFt": 150
      },
      {
        "leIdent": "10R",
        "heIdent": "28L",
        "le": [
          41.957199,
          -87.927902
        ],
        "he": [
          41.957245,
          -87.900291
        ],
        "widthFt": 150
      }
    ]
  },
  "VIDP": {
    "icao": "VIDP",
    "iata": "DEL",
    "name": "Indira Gandhi International Airport",
    "centerLat": 28.55563,
    "centerLon": 77.09519,
    "label": "DEL — Indira Gandhi International Airport",
    "runways": [
      {
        "leIdent": "09",
        "heIdent": "27",
        "le": [
          28.570499,
          77.087997
        ],
        "he": [
          28.569799,
          77.116997
        ],
        "widthFt": 148
      },
      {
        "leIdent": "10",
        "heIdent": "28",
        "le": [
          28.5672,
          77.084801
        ],
        "he": [
          28.5585,
          77.122498
        ],
        "widthFt": 148
      },
      {
        "leIdent": "11L",
        "heIdent": "29R",
        "le": [
          28.550125,
          77.068176
        ],
        "he": [
          28.540747,
          77.111877
        ],
        "widthFt": 148
      },
      {
        "leIdent": "11R",
        "heIdent": "29L",
        "le": [
          28.547171,
          77.065491
        ],
        "he": [
          28.537729,
          77.109528
        ],
        "widthFt": 197
      }
    ]
  }
};
